CREATE TABLE IF NOT EXISTS books(
  ID INT PRIMARY KEY  NOT NULL,
  TITLE TEXT,
  PRICE MONEY
);

CREATE TABLE IF NOT EXISTS authors(
  ID INT PRIMARY KEY  NOT NULL,
  NAME TEXT
);

CREATE TABLE IF NOT EXISTS books_ordered(
);

CREATE TABLE IF NOT EXISTS orders(
  ID INT PRIMARY KEY  NOT NULL
);

CREATE TABLE IF NOT EXISTS customers(
  ID INT PRIMARY KEY  NOT NULL
);
